### ISSUE TITLE
--lxc-conf was removed from Docker engine

### ISSUE THREAD

**Issue by cesdperez** [fgsch/docker-webex#3]
[LXC built-in exec driver](https://docs.docker.com/engine/deprecated/#lxc-built-in-exec-driver) has been removed. When I run `./webex.sh` I get `unknown flag: --lxc-conf`.

Any way around this? thanks

**Comment by fgsch** [comment]
Until I have time to review it and check what the alternatives are you can use the `--privileged` option.

**Comment by cesdperez** [comment]
Don't worry, they just announced a new webapp https://chrome.google.com/webstore/detail/cisco-webex-app-for-chrom/fceempjejlfaadkgdacpfhheknndlcjl?hl=en-US. I just tested it with Chrome on Arch Linux and it works fine. Finally Cisco! welcome to 2017 :P

**Comment by Chi-teck** [comment]
@cesdperez does "Sharing screen" option works for you in that application?

**Comment by cesdperez** [comment]
no, you can't share your screen with the webapp. it's enough for me though.

**Comment by fgsch** [comment]
Addressed in 60aa1b41157c1b196d086edfd445c6f5327d8bff.
